services:
    website.command.updatedocs:
        class: ConcertoCms\Website\Command\UpdateDocsCommand
        arguments:
            - @concerto_cms_core.content
            - @markdown.parser.max
        tags:
            -  { name: console.command }