services:
    website.controller.page:
        class: ConcertoCms\Website\Controller\PageController
        arguments:
            - @templating
            - @concerto_cms_core.content
            - @router